Update metrics.yml

diff --git a/.github/workflows/metrics.yml b/.github/workflows/metrics.yml
--- a/.github/workflows/metrics.yml
+++ b/.github/workflows/metrics.yml
@@ -12,7 +12,7 @@ jobs:
       - name: Checkout del repository
         uses: actions/checkout@v2
 
-      - name: Install Docker
+      - name: Install Dependencies
         run: |
           sudo apt-get update
           sudo apt-get install -y \
@@ -20,7 +20,8 @@ jobs:
             ca-certificates \
             curl \
             gnupg-agent \
-            software-properties-common
+            software-properties-common \
+            jq
           curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
           sudo add-apt-repository \
             "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
@@ -29,8 +30,14 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y docker-ce docker-ce-cli containerd.io
 
-      - name: Install jq
-        run: sudo apt-get install -y jq
+      - name: Verify Dependencies
+        run: |
+          for DEPENDENCY in docker jq; do
+            if ! which $DEPENDENCY > /dev/null 2>&1; then
+              echo "::error::\"$DEPENDENCY\" is not installed on current runner but is needed to run metrics"
+              exit 1
+            fi
+          done
 
       - name: Genera il file metrics con lingue, statistiche e attività
         uses: lowlighter/metrics@latest
@@ -55,4 +62,4 @@ jobs:
 
           # Configurazioni facoltative
           custom_title: 'Statistiche del mio GitHub'
-          custom_footer: 'Generated by lowlighter/metrics and the file is located in directory robbietto/.github/workflows/metrics.yml, same as readme file.'
+          custom_footer: 'Generated by lowlighter/metrics'
